### ISSUE TITLE
RPi2 

### ISSUE THREAD

**Issue by uecasm** [notro/rpi-build#11]
I'm currently using a Rakefile like this:

    require 'mylib/my-kernel'

    release :pi1 => :my_rpi_common do
    end

    release :pi2 => :my_rpi_common do
        ENV['LINUX_DEFCONFIG'] = 'bcm2709_defconfig'
    end

And then building like this:

    rpi-build use[mylib] pi1 clean build
    rpi-build use[mylib] pi2 clean build WORKDIR=workdir7

(Two separate installs are also required to produce a card with both kernels.)

This seems to work, but I'm sure it's doing some steps redundantly.  Is it possible to streamline this into a single build that does both kernels?  Or is there some better way to do this?  (I couldn't find a way to change the default WORKDIR inside the Rakefile based on the release, which would have been nice.)

Maybe the wiki could be updated with a Pi2 example as well?

**Comment by notro** [comment]
Please do update the wiki. Anyone with a github account can do that. I don't have time to maintain this anymore: https://github.com/notro/rpi-build/wiki

This my notes from what I did with my latest FBTFT kernel release. You need two separate builds. ccache could speed things up, but I have never tried it.
```
WORKDIR=workdir.bcm2709 rpi-build clean log fbtft_master build LINUX_DEFCONFIG=bcm2709_defconfig

WORKDIR=workdir.bcm2708 rpi-build clean log fbtft_master build LINUX_DEFCONFIG=bcmrpi_defconfig

# redo these if a target has been rebuilt.
cp workdir.bcm2708/out/{kernel.img,Module.symvers} workdir.bcm2709/out/
cp -r workdir.bcm2708/out/modules/* workdir.bcm2709/out/modules/
cp workdir.bcm2708/out/extra/{System.map,.config,version} workdir.bcm2709/out/extra/

WORKDIR=workdir.bcm2709 rpi-build fbtft_master install SSHIP=192.168.10.120

WORKDIR=workdir.bcm2709 rpi-build fbtft_master commit
WORKDIR=workdir.bcm2709 rpi-build fbtft_master push
```

**Comment by uecasm** [comment]
Ok, just before I try to update the wiki (I was thinking of making a separate page), let me run something past you to see if it's sane:

I've made a script that's largely similar to the above, but instead of copying one workdir into the other it creates a third workdir from those two.  It copies across `out`, `*.targets`, and `*.variables`.  It does *not* copy across `firmware`, `linux`, `tools`, or any other subdirs unless they were already copied into `out`.

I've verified that `rpi-build release install` works on this third workdir.  I haven't tested commit/push etc as I don't use those myself.  Do you anticipate any problems with this approach?

**Comment by notro** [comment]
That is a cleaner approach.

I assume ```release``` is a target you've made?

```commit``` dependes on the ```readme``` target which will fail to run in the third workdir: https://github.com/notro/rpi-build/blob/master/targets.rake#L138
If ```readme``` is used instead of ```build``` in the others, it should be ok for ```commit``` to work.
But you can always just make a note of this shortcoming in the wiki also if you don't want to use readme instead of build.

**Comment by uecasm** [comment]
Actually "release" was just a placeholder for whatever the release in the Rakefile was.  eg. `fbtft_master` in your case.

Maybe I'm missing something, but it doesn't look like that the `readme` target would fail.  Admittedly I don't really know Ruby code but it looks like it's only looking at a git repository which is outside of the workdir.

Having said that, it does fail on my one, but then it fails in exactly the same way on the original workdirs as well.  I assume there's some sort of setup step that I'm missing.  (Looking through the wiki page, I never did the `git clone` step, so I don't have an `FW_REPO` anyway.)  But as far as I can tell, the instructions put that dir in the same location as the `Rakefile` (or possibly the `pwd` -- again I'm not quite familiar enough with Ruby to tell the difference), so it should be outside of the workdir and immune to this.

**Comment by notro** [comment]
Yes you're right. My bad :-)

**Comment by uecasm** [comment]
Done: https://github.com/notro/rpi-build/wiki/RaspberryPi2

**Comment by notro** [comment]
Nice.

**Comment by notro** [comment]
Based on your work I have made a **merge** target: https://github.com/notro/rpi-build/commit/83429762253bd8d2782541063fcd19a41b74a3cf

My latest release was done like this:
```
WORKDIR=workdir.bcm2708 LINUX_DEFCONFIG=bcmrpi_defconfig  rpi-build clean log fbtft_master build
WORKDIR=workdir.bcm2709 LINUX_DEFCONFIG=bcm2709_defconfig rpi-build clean log fbtft_master build

rpi-build fbtft_master merge install SSHIP=192.168.10.129

rpi-build fbtft_master commit
rpi-build fbtft_master push

```

**Comment by uecasm** [comment]
Nice.  Although I still prefer using a script to avoid having to remember the variables each time.  But it can be simplified now.
